/** Tailwind v3 mapeado 1:1 desde resources/style-guide.json
 * (tokens extraidos del tailwind.config inline de Stitch). */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#b8c4ff',
        'inverse-surface': '#213145',
        'on-background': '#0b1c30',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#a8b8ff',
        'on-primary-fixed': '#001453',
        'on-primary-fixed-variant': '#173bab',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#003ea8',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444653',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b4bbd5',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        outline: '#757684',
        'outline-variant': '#c4c5d5',
        primary: '#00288e',
        'primary-container': '#1e40af',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b8c4ff',
        secondary: '#0051d5',
        'secondary-container': '#316bf3',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cbdbf5',
        'surface-tint': '#3755c3',
        'surface-variant': '#d3e4fe',
        tertiary: '#2d3449',
        'tertiary-container': '#434b60',
        'tertiary-fixed': '#dae2fd',
        'tertiary-fixed-dim': '#bec6e0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.375rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        margin: '1.5rem',
        'margin-dense': '1rem',
        gutter: '1rem',
        'gutter-dense': '0.5rem',
      },
      fontFamily: {
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'code-tabular': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['0.9375rem', { lineHeight: '1.375rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0em', fontWeight: '400' }],
        'code-tabular': ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['0.8125rem', { lineHeight: '1rem', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '0.9375rem', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
